export const BUNGO_FETCH = 'BUNGO_FETCH';
export const BUNGO_FETCH_SUCCESS = 'BUNGO_FETCH_SUCCESS';
export const BUNGO_FETCH_FAILURE = 'BUNGO_FETCH_FAILURE';
export const GET_MEMBERSHIPS = 'GET_MEMBERSHIPS';
export const FUCKING_ERROR = 'FUCKING_ERROR';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_PROFILE = 'GET_PROFILE';